### ISSUE TITLE
Cannot get working

### ISSUE THREAD

**Issue by juicyslew** [RobQuistNL/P3DC#1]
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object controller:

Error defining an external function.
 at gml_Script_p3dc_init (line 24) - global.p3dc_bs3 = external_define(n,"bs3",dll_cdecl,ty_real,6,ty_real,ty_real,ty_real,ty_real,ty_real,ty_real);
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_p3dc_init (line 24)
called from - gml_Object_controller_CreateEvent_1 (line 4) - p3dc_init()

I keep getting this error for numerous of the externally defined functions in p3dc init, i don't even know what this means?

**Comment by RobQuistNL** [comment]
It means that the DLL could not be initialized. This function is trying to open DLL "n" and load in the function "bs3" from it. Are you sure the DLL file is there?

**Comment by juicyslew** [comment]
Yes I am sure, Also I have learned more about the problem.  Apparently the current version of game maker studio has a bug that doesn't allow externally defined functions with more than 4 variables, causing this error

Here is a link to the bug page:
http://bugs.yoyogames.com/view.php?id=23281

**Comment by juicyslew** [comment]
For now I am just going to try to revert to 1.4.1757 which i think is the most recent one before that bug existed.  If you have a better solution please tell me 👍

Edit: 1.4.1757 is working, or at least not crashing, still need to go through the steps to generate the map.

**Comment by RobQuistNL** [comment]
Ah cool! Glad to see its not in here... Allthough now its much harder to fix, knowing YoYo this is going to take forever :)

**Comment by juicyslew** [comment]
True :P

**Comment by RobQuistNL** [comment]
Jij bent Nederlands, of niet?
